development:
  facebook:
    consumer_key: 140973972639188
    consumer_secret: 3f3290508b7e87346bea83b784d2d000
  twitter:
    consumer_key: bvRFWt6ZbF9LGV7PnA
    consumer_secret: l5GfIJGy3YOJwkw7YkvLu3m19oBYYCShE6WtmsLQXk
  google:
    consumer_key: 618953607369.apps.googleusercontent.com
    consumer_secret: oXof5eKdr3VfQYQIT-cYfoWu

test:
  facebook:
    consumer_key: 140973972639188
    consumer_secret: 3f3290508b7e87346bea83b784d2d000
  twitter:
    consumer_key: bvRFWt6ZbF9LGV7PnA
    consumer_secret: l5GfIJGy3YOJwkw7YkvLu3m19oBYYCShE6WtmsLQXk
  google:
    consumer_key: 618953607369.apps.googleusercontent.com
    consumer_secret: oXof5eKdr3VfQYQIT-cYfoWu

production:
  facebook:
    consumer_key: 249148091834756
    consumer_secret: fb9f3011e1a5878d5c3f29f21cfdc024
  twitter:
    consumer_key: 8YeAE49LAmUcmwLBpVIQA
    consumer_secret: BfHNStRRpfjClbvd1GnbdD1j5N5aEJk2YkAXZfktaU
  google:
    consumer_key: 618953607369-tc3ipnuggd0k8cjrrta6f2g2q4g1sfhk.apps.googleusercontent.com
    consumer_secret: a_ZHYdsnxv1YtU5CcBcIKwGe
